{
 "title": "Kube Dashboard",
 "time": { "from": "2025-07-27T05:56:41.238Z", "to": "2025-07-27T06:06:41.238Z" },
 "templating": {
  "list": [
   {
    "name": "Server",
    "query": {
     "query": "label_values(node_boot_time_seconds,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Percent Disk Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=\"$Server\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\",instance=\"$Server\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=\"$Server\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"$Server\"} - node_memory_MemFree_bytes{instance=\"$Server\"}  - node_memory_Buffers_bytes{instance=\"$Server\"} - node_memory_Cached_bytes{instance=\"$Server\"}) / node_memory_MemTotal_bytes{instance=\"$Server\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Core Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 15, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"$Server\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Disk",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=\"$Server\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\",instance=\"$Server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumed Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=\"$Server\"} - node_memory_MemFree_bytes{instance=\"$Server\"}  - node_memory_Buffers_bytes{instance=\"$Server\"} - node_memory_Cached_bytes{instance=\"$Server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$Server\",device!~\"lo\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$Server\",device!~\"lo\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Disk Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=\"$Server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$Server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods per namespace",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Pods per Namespace",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}