apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-hostpath-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-pv
  hostPath:
    path: /data/prometheus

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-pv
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain