apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name  }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: app
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        